import js from '@eslint/js';
import tseslint from 'typescript-eslint';

const browserGlobals = {
    window: 'readonly',
    document: 'readonly',
    console: 'readonly',
    localStorage: 'readonly',
    indexedDB: 'readonly',
    URL: 'readonly',
    Blob: 'readonly',
    FileReader: 'readonly',
    setTimeout: 'readonly',
    clearTimeout: 'readonly',
    setInterval: 'readonly',
    clearInterval: 'readonly',
    Promise: 'readonly',
    JSON: 'readonly',
    Date: 'readonly',
    Error: 'readonly',
    Array: 'readonly',
    Object: 'readonly',
    String: 'readonly',
    Number: 'readonly',
    Boolean: 'readonly',
    RegExp: 'readonly',
    Map: 'readonly',
    Set: 'readonly',
    confirm: 'readonly',
    prompt: 'readonly',
    alert: 'readonly',
    ResizeObserver: 'readonly',
    performance: 'readonly',
    PerformanceObserver: 'readonly',
    requestAnimationFrame: 'readonly',
    CustomEvent: 'readonly',
    KeyboardEvent: 'readonly',
    module: 'readonly',
    require: 'readonly',
    Formatter: 'readonly',
    DashboardStorage: 'readonly',
    Validator: 'readonly',
    ThemeManager: 'readonly',
    DataManager: 'readonly',
    UIManager: 'readonly',
    HistoryManager: 'readonly',
    ChartRenderer: 'readonly',
    PerformanceOptimizer: 'readonly',
};

const styleRules = {
    'no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
    'no-console': 'off',
    'no-debugger': 'warn',
    'prefer-const': 'error',
    'no-var': 'error',
    'object-shorthand': 'error',
    'prefer-arrow-callback': 'error',
    semi: ['error', 'always'],
    quotes: ['error', 'single'],
    indent: ['error', 4, { SwitchCase: 1 }],
    'comma-dangle': ['error', 'always-multiline'],
    'eol-last': 'error',
    'no-trailing-spaces': 'error',
    'max-len': ['error', { code: 120 }],
    eqeqeq: ['error', 'always', { null: 'ignore' }],
    curly: 'error',
    'default-case': 'error',
    'no-duplicate-imports': 'error',
    'no-template-curly-in-string': 'error',
};

export default [
    {
        ignores: [
            'node_modules/',
            'dist/',
            'build/',
            '*.min.js',
            'src/__mocks__/',
            'src/__tests__/',
            '**/._*',
            'src/types/**',
        ],
    },
    js.configs.recommended,
    {
        files: ['**/*.js'],
        languageOptions: {
            ecmaVersion: 2022,
            sourceType: 'module',
            globals: browserGlobals,
        },
        rules: styleRules,
    },
    {
        files: ['**/*.ts'],
        plugins: {
            '@typescript-eslint': tseslint.plugin,
        },
        languageOptions: {
            parser: tseslint.parser,
            ecmaVersion: 2022,
            sourceType: 'module',
            globals: browserGlobals,
        },
        rules: {
            ...styleRules,
            'no-undef': 'off',
            'no-unused-vars': 'off',
            '@typescript-eslint/no-unused-vars': ['error', {
                argsIgnorePattern: '^_',
                varsIgnorePattern: '^_',
                caughtErrors: 'none',
            }],
            'max-len': ['error', {
                code: 120,
                ignoreStrings: true,
                ignoreTemplateLiterals: true,
                ignoreComments: true,
            }],
        },
    },
];
